name: Multi-Platform Build and Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ github.ref_name }}
          path: dist/
          retention-days: 3

  verify:
    name: Verify Build Artifact
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded

      - name: List downloaded artifacts
        run: ls -R downloaded

      - name: Check if index.html exists in any build output
        run: |
          found=$(find downloaded -type f -name "index.html" | wc -l)
          if [ "$found" -eq 0 ]; then
            echo "index.html not found in any build output"
            exit 1
          else
            echo "index.html found in $found location(s)"
          fi
